---
title: "Quiz4"
author: "Sumit Kamra"
date: "9/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Q1: Using strsplit
```{r}
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv",
              destfile = "file.csv", method = "curl")
dat <- read.csv("file.csv")
head(dat)

```
```{r}
names(dat)
```
```{r}
strsplit(names(dat),"\\wgtp")[123]
```

## Q2: Reading GDP data
```{r}
file_url<-"https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv"
download.file(file_url, destfile = "gdp.csv", method = "curl")
gdp_data <- read.csv("gdp.csv", skip = 4)
gdp_data <- gdp_data[1:190,]
```

#### Removing , from gdp
```{r}
gdp_data$X.4 <- as.numeric(
                        gsub(",", "", gdp_data$X.4)
)
```

```{r}
mean(gdp_data$X.4)
```
## Q3. Find country names starting with United

```{r}
library(dplyr)
gdp_data <- rename(gdp_data, countryName = X)
table(grepl("^United", gdp_data$X.3))
```
## Q4: Merging two data sets
```{r}
education_url = "https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv"

download.file(education_url, destfile = "education.csv", method = "curl")

gdp <- read.csv("gdp.csv", skip = 4)
gdp <- gdp_data[1:190,]
education <- read.csv("education.csv")

names(gdp)
names(education)

```

```{r}
mergedData <- merge(gdp, education, by.x = "countryName", 
                    by.y = "CountryCode", all = FALSE)
head(mergedData)
```

#### Identify fiscal year in special notes
```{r}

table(grepl("Fiscal year end: [Jj]une", mergedData$Special.Notes))

```

## Q:5 Using Stock Data
```{r}
library(quantmod)
amzn = getSymbols("AMZN",auto.assign=FALSE)
sampleTimes = index(amzn)
```
```{r}
library(lubridate)
table(year(sampleTimes), weekdays(sampleTimes))
```

